.TH gl_copyscreen 3 "2 Aug 1997" "Svgalib (>= 1.2.11)" "Svgalib User Manual"
.SH NAME
gl_copyscreen \- copy the screen contents of contexts

.SH SYNOPSIS
.B #include <vgagl.h>

.BI "void gl_copyscreen(GraphicsContext *" gc );

.SH DESCRIPTION
Copy the current graphics context contents (screen data) to
the specified graphics context (the physical screen, for
example). Contexts are assumed to be identical in size.

.SH SEE ALSO

.BR svgalib (7),
.BR vgagl (7),
.BR svgalib.conf (5),
.BR threedkit (7),
.BR testgl (1),
.BR plane (1),
.BR wrapdemo (1),
.BR currentcontext (3),
.BR gl_allocatecontext (3),
.BR gl_clearscreen (3),
.BR gl_copybox (3),
.BR gl_copyboxfromcontext (3),
.BR gl_copyboxtocontext (3),
.BR gl_fillbox (3),
.BR gl_getbox (3),
.BR gl_putbox (3).

.SH AUTHOR

This manual page was edited by Michael Weller <eowmob@exp-math.uni-essen.de>. The
exact source of the referenced demo as well as of the original documentation is
unknown.

It is very likely that both are at least to some extent are due to
Harm Hanemaayer <H.Hanemaayer@inter.nl.net>.

Occasionally this might be wrong. I hereby
asked to be excused by the original author and will happily accept any additions or corrections
to this first version of the svgalib manual.
