.TH gl_circle 3 "2 Aug 1997" "Svgalib (>= 1.2.11)" "Svgalib User Manual"
.SH NAME
gl_circle \- draw a circle

.SH SYNOPSIS
.B #include <vgagl.h>

.BI "void gl_circle(int " x ", int " y ", int " r ", int " c );

.SH DESCRIPTION
Draw a circle of radius
.I r
in color
.IR c ,
centered at
.RI ( x ", " y ).

.SH SEE ALSO
.BR svgalib (7),
.BR vgagl (7),
.BR svgalib.conf (5),
.BR threedkit (7),
.BR testgl (1),
.BR plane (1),
.BR wrapdemo (1),
.BR gl_clearscreen (3),
.BR gl_colorfont (3),
.BR gl_disableclipping (3),
.BR gl_enableclipping (3),
.BR gl_fillbox (3),
.BR gl_hline (3),
.BR gl_line (3),
.BR gl_setclippingwindow (3),
.BR gl_setpalette (3),
.BR gl_setpalettecolor (3),
.BR gl_setpalettecolors (3),
.BR gl_setpixel (3),
.BR gl_setpixelrgb (3),
.BR gl_setrgbpalette (3),
.BR gl_setwritemode (3).

.SH AUTHOR

This manual page was edited by Michael Weller <eowmob@exp-math.uni-essen.de>. The
exact source of the referenced demo as well as of the original documentation is
unknown.

It is very likely that both are at least to some extent are due to
Harm Hanemaayer <H.Hanemaayer@inter.nl.net>.

Occasionally this might be wrong. I hereby
asked to be excused by the original author and will happily accept any additions or corrections
to this first version of the svgalib manual.
