.TH gl_expandfont 3 "2 Aug 1997" "Svgalib (>= 1.2.11)" "Svgalib User Manual"
.SH NAME
gl_expandfont \- expand a packed pixel font

.SH SYNOPSIS
.B #include <vgagl.h>

.BI "void gl_expandfont(int " fw ", int " fh ", int " c ", void *" sfp ", void *" dfp );

.SH DESCRIPTION
Convert a bit-per-pixel font at
.IR sfp
with 256 characters of size
.RI ( fw ", " fh )
to an expanded font of character pixmaps, stored at
.I dfp
(size will be 256 *
.IR fw " * " fw
.RB " * " BYTESPERPIXEL ).
All non-zero pixels are set to color
.IR c .

It is possible to use non expanded fonts (but it is slower) when
the
.BR "FONT_COMPRESSED gl_setwritemode" (3)
flag is set.

.SH SEE ALSO

.BR svgalib (7),
.BR vgagl (7),
.BR svgalib.conf (5),
.BR testgl (1),
.BR gl_colorfont (3),
.BR gl_font8x8 (3),
.BR gl_setfont (3),
.BR gl_setfontcolors (3),
.BR gl_setwritemode (3),
.BR gl_write (3),
.BR gl_writen (3).

.SH AUTHOR

This manual page was edited by Michael Weller <eowmob@exp-math.uni-essen.de>. The
exact source of the referenced demo as well as of the original documentation is
unknown.

It is very likely that both are at least to some extent are due to
Harm Hanemaayer <H.Hanemaayer@inter.nl.net>.

Occasionally this might be wrong. I hereby
asked to be excused by the original author and will happily accept any additions or corrections
to this first version of the svgalib manual.
