.TH gl_enableclipping 3 "2 Aug 1997" "Svgalib (>= 1.2.11)" "Svgalib User Manual"
.SH NAME
gl_enableclipping \- enables clipping

.SH SYNOPSIS
.B #include <vgagl.h>

.BI "void gl_enableclipping(void);"

.SH DESCRIPTION
Enable automatic clipping in most functions. No, I don't know
which ones. However, it works for most.
.BR gl_copybox (3)
is report to do no clipping.

Go figure.

.SH SEE ALSO

.BR svgalib (7),
.BR vgagl (7),
.BR svgalib.conf (5),
.BR threedkit (7),
.BR testgl (1),
.BR plane (1),
.BR wrapdemo (1),
.BR gl_disableclipping (3),
.BR gl_setclippingwindow (3).

.SH AUTHOR

This manual page was edited by Michael Weller <eowmob@exp-math.uni-essen.de>. The
exact source of the referenced demo as well as of the original documentation is
unknown.

It is very likely that both are at least to some extent are due to
Harm Hanemaayer <H.Hanemaayer@inter.nl.net>.

Occasionally this might be wrong. I hereby
asked to be excused by the original author and will happily accept any additions or corrections
to this first version of the svgalib manual.
