.TH gl_setcontextvgavirtual 3 "2 Aug 1997" "Svgalib (>= 1.2.11)" "Svgalib User Manual"
.SH NAME
gl_setcontextvgavirtual \- set the context to a virtual mode

.SH SYNOPSIS
.B #include <vgagl.h>

.BI "int gl_setcontextvgavirtual(int " mode );

.SH DESCRIPTION
Allocate a virtual screen in system memory identical to
the graphics mode (as defined in
.BR vga_setmode (3)),
and make that the current graphics context.

The function returns 0 for success and non-zero if the mode is not supported by the
hardware.

The only thing you can do with a planar (mode X-like)
256 color mode is aligned
.BR gl_putbox ,
and use it as a target for
.BR gl_copyscreen .

.SH SEE ALSO
.BR svgalib (7),
.BR vgagl (7),
.BR svgalib.conf (5),
.BR threedkit (7),
.BR testgl (1),
.BR currentcontext (3),
.BR gl_allocatecontext (3),
.BR gl_copyboxfromcontext (3),
.BR gl_copyboxtocontext (3),
.BR gl_copyscreen (3),
.BR gl_freecontext (3),
.BR gl_getcontext (3),
.BR gl_setcontext (3),
.BR gl_setcontextheight (3),
.BR gl_setcontextvga (3),
.BR gl_setcontextvirtual (3),
.BR gl_setcontextwidth (3).

.SH AUTHOR

This manual page was edited by Michael Weller <eowmob@exp-math.uni-essen.de>. The
exact source of the referenced demo as well as of the original documentation is
unknown.

It is very likely that both are at least to some extent are due to
Harm Hanemaayer <H.Hanemaayer@inter.nl.net>.

Occasionally this might be wrong. I hereby
asked to be excused by the original author and will happily accept any additions or corrections
to this first version of the svgalib manual.
