.TH keyboard_update 3 "27 July 1997" "Svgalib (>= 1.2.11)" "Svgalib User Manual"
.SH NAME
keyboard_update, keyboard_waitforupdate \- process raw keyboard events
.SH SYNOPSIS

.B "#include <vgakeyboard.h>"

.BI "int keyboard_update(void);
.br
.BI "void keyboard_waitforupdate(void);

.SH DESCRIPTION
These routines check the keyboard buffer for any raw keyboard events and do the
necessary updates to the internal buffers of
.BR keyboard_clearstate (3)
and
.BR keyboard_keypressed (3).

When there are no such events,
.B keyboard_update()
returns 0 immediately (non-zero else) whereas
.B keyboard_waitforupdate()
blocks and waits until an event occurs.

.BR vga_waitevent (3)
allows to wait for keyboard and other events at the same time.

.SH SEE ALSO

.BR svgalib (7),
.BR vgagl (7),
.BR libvga.config (5),
.BR keytest (6),
.BR eventtest (6),
.BR keyboard_seteventhandler (3),
.BR keyboard_init (3),
.BR keyboard_init_return_fd (3),
.BR keyboard_close (3),
.BR keyboard_setdefaulteventhandler (3),
.BR keyboard_getstate (3),
.BR keyboard_clearstate (3),
.BR keyboard_translatekeys (3),
.BR keyboard_keypressed (3),
.BR vga_waitevent (3)

.SH AUTHOR

This manual page was edited by Michael Weller <eowmob@exp-math.uni-essen.de>. The
exact source of the referenced function as well as of the original documentation is
unknown.

It is very likely that both are at least to some extent are due to
Harm Hanemaayer <H.Hanemaayer@inter.nl.net>.

Occasionally this might be wrong. I hereby
asked to be excused by the original author and will happily accept any additions or corrections
to this first version of the svgalib manual.
