.TH mouse_update 3 "27 July 1997" "Svgalib (>= 1.2.11)" "Svgalib User Manual"
.SH NAME
mouse_update \- updates the mouse state
.SH SYNOPSIS

.B "#include <vgamouse.h>"

.BI "int mouse_update(void);"

.SH DESCRIPTION
This reads in mouse events from the mouse buffer and updates
the internal svgalib variables which store the current mouse
position and button states. If there are no events to be
read this routine returns immediately.

The function returns 0 if there was no event and a non-zero value otherwise.
.SH SEE ALSO

.BR svgalib (7),
.BR vgagl (7),
.BR libvga.config (5),
.BR eventtest (6),
.BR mouse_close (3),
.BR mouse_init (3),
.BR mouse_getposition_6d (3),
.BR mouse_setposition (3),
.BR mouse_setscale (3),
.BR mouse_setwrap (3),
.BR mouse_setxrange (3),
.BR mouse_getx (3),
.BR mouse_waitforupdate (3),
.BR vga_setmousesupport (3),
.BR mouse_seteventhandler (3),
.BR vga_waitevent (3)
.SH AUTHOR

This manual page was edited by Michael Weller <eowmob@exp-math.uni-essen.de>. The
exact source of the referenced function as well as of the original documentation is
unknown.

It is very likely that both are at least to some extent are due to
Harm Hanemaayer <H.Hanemaayer@inter.nl.net>.

Occasionally this might be wrong. I hereby
asked to be excused by the original author and will happily accept any additions or corrections
to this first version of the svgalib manual.
