.TH vga_hasmode 3 "27 July 1997" "Svgalib (>= 1.2.11)" "Svgalib User Manual"
.SH NAME
vga_hasmode \- returns if a video mode is supported
.SH SYNOPSIS

.B "#include <vga.h>"

.BI "int vga_hasmode(int " mode );

.SH DESCRIPTION
The function returns a non-zero value if the given
.I mode
is supported and 0 else.  See
.BR vga_setmode (3)
for a list of predefined
.I mode
values and their meaning.
.BR vga_modeinfo (3)
can be used to find out details about the specific mode.

.SH SEE ALSO

.BR svgalib (7),
.BR vgagl (7),
.BR libvga.config (5),
.BR vgatest (6),
.BR vga_modeinfo (3),
.BR vga_setmode (3),
.BR vga_lastmodenumber (3),
.BR vga_getmodename (3),
.BR vga_getmodenumber (3)
.BR vga_getcurrentmode (3)
.SH AUTHOR

This manual page was edited by Michael Weller <eowmob@exp-math.uni-essen.de>. The
exact source of the referenced function as well as of the original documentation is
unknown.

It is very likely that both are at least to some extent are due to
Harm Hanemaayer <H.Hanemaayer@inter.nl.net>.

Occasionally this might be wrong. I hereby
asked to be excused by the original author and will happily accept any additions or corrections
to this first version of the svgalib manual.
