.TH vga_selectcursor 3 "23 June 2001" "Svgalib (>= 1.9.6)" "Svgalib User Manual"
.SH NAME
vga_selectcursor \- select mouse cursor pattern
.SH SYNOPSIS

.B "#include <vga.h>"

.BI "void vga_selectcursor(int cur);"

.SH DESCRIPTION
Selects onr of the 16 cursor patterns to display.

.SH SEE ALSO

.BR svgalib (7),
.BR mouse_init (3),
.BR vga_showcursor (3),
.BR vga_initcursor (3),
.BR vga_setcursorposition (3),
.BR vga_setcursorimage (3),

.SH AUTHOR

This manual page written by Matan Ziv-Av <matan@svgalib.org>.

